version: "3.8"
services:
  database:
    container_name: velikoWeb
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - ../var/dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: velikoWeb-pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
    links:
      - database

  mock-veliko-api:
    container_name: mock-veliko-api
    image: bfoujols/mock-veliko-api:latest
    ports:
      - "9042:80"

networks:
  dev:

volumes:
  db-data: